<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE orders [
        <!ELEMENT orders (item+)>
        <!ELEMENT item (itemNumber,description,quantity,price)>
        <!ELEMENT itemNumber      (#PCDATA)>
        <!ELEMENT description    (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT price    (#PCDATA)>
]>

<orders>
    <item>
        <itemNumber>ksu-0652</itemNumber>
        <description>双飞燕键盘</description>
        <quantity>1</quantity>
        <price>35.00</price>
    </item>
    <item>
        <itemNumber>ksu-7720</itemNumber>
        <description>intel CPU</description>
        <quantity>1</quantity>
        <price>1650.00</price>
    </item>
    <item>
        <itemNumber>ksu-7010</itemNumber>
        <description>迈拓硬盘</description>
        <quantity>1</quantity>
        <price>850.00</price>
    </item>
</orders>